### ISSUE TITLE
Not able to build on recent Arch Linux

### ISSUE THREAD

**Issue by brandflake11** [Drumfix/avb4linux#3]
When I try to make, I am getting this error:
$ make
mkdir -p kernel-module/igb && make  subdir=kernel-module/igb  -C kernel-module/igb 
make[1]: Entering directory '/home/brandon/sourceforge/avb4linux/kernel-module/igb'
make -C /lib/modules/5.2.10-arch1-1-ARCH/build SUBDIRS=/home/brandon/sourceforge/avb4linux/kernel-module/igb modules
make[2]: Entering directory '/usr/lib/modules/5.2.10-arch1-1-ARCH/build'
Makefile:213: ================= WARNING ================
Makefile:214: 'SUBDIRS' will be removed after Linux 5.3
Makefile:215: Please use 'M=' or 'KBUILD_EXTMOD' instead
Makefile:216: ==========================================
  CC [M]  /home/brandon/sourceforge/avb4linux/kernel-module/igb/igb_main.o
/home/brandon/sourceforge/avb4linux/kernel-module/igb/igb_main.c:2391:22: error: initialization of ‘u16 (*)(struct net_device *, struct sk_buff *, struct net_device *)’ {aka ‘short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *)’} from incompatible pointer type ‘u16 (*)(struct net_device *, struct sk_buff *, struct net_device *, u16 (*)(struct net_device *, struct sk_buff *, struct net_device *))’ {aka ‘short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *, short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *))’} [-Werror=incompatible-pointer-types]
 2391 |  .ndo_select_queue = igb_select_queue,
      |                      ^~~~~~~~~~~~~~~~
/home/brandon/sourceforge/avb4linux/kernel-module/igb/igb_main.c:2391:22: note: (near initialization for ‘igb_netdev_ops.ndo_select_queue’)
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:279: /home/brandon/sourceforge/avb4linux/kernel-module/igb/igb_main.o] Error 1
make[2]: *** [Makefile:1597: _module_/home/brandon/sourceforge/avb4linux/kernel-module/igb] Error 2
make[2]: Leaving directory '/usr/lib/modules/5.2.10-arch1-1-ARCH/build'
make[1]: *** [Makefile:264: default] Error 2
make[1]: Leaving directory '/home/brandon/sourceforge/avb4linux/kernel-module/igb'
make: *** [Makefile:31: igb] Error 2

What might this be?

**Comment by Drumfix** [comment]
Grrr, the function prototype of ndo_select_queue has been changed in kernel 5.2.
The fallback parameter has been removed, so igb_select_queue has to be change accordingly.

Quickfix: Replace the prototype of igb_select_queue in igb_main.c by the one your kernel is actually using.

For 5.2 the prototype is 

static u16 igb_select_queue(struct net_device *dev, struct sk_buff *skb,
			    struct net_device *sb_dev)

**Comment by brandflake11** [comment]
Hey, thanks for getting back!

I am not sure what igb_select_queue to change. There seems to be 6 lines that igb_select_queue exists on (I am sorry, I am not super great at C++), inside an if else statement. I tried changing all 6 of them, tried to make it, and got this:

$ make
mkdir -p kernel-module/igb && make  subdir=kernel-module/igb  -C kernel-module/igb 
make[1]: Entering directory '/home/brandon/sourceforge/avb4linux/kernel-module/igb'
make -C /lib/modules/5.2.11-arch1-1-ARCH/build SUBDIRS=/home/brandon/sourceforge/avb4linux/kernel-module/igb modules
make[2]: Entering directory '/usr/lib/modules/5.2.11-arch1-1-ARCH/build'
Makefile:213: ================= WARNING ================
Makefile:214: 'SUBDIRS' will be removed after Linux 5.3
Makefile:215: Please use 'M=' or 'KBUILD_EXTMOD' instead
Makefile:216: ==========================================
  CC [M]  /home/brandon/sourceforge/avb4linux/kernel-module/igb/igb_main.o
/home/brandon/sourceforge/avb4linux/kernel-module/igb/igb_main.c:5830:1: error: expected identifier or ‘(’ before ‘{’ token
 5830 | {
      | ^
/home/brandon/sourceforge/avb4linux/kernel-module/igb/igb_main.c:5820:12: warning: ‘igb_select_queue’ declared ‘static’ but never defined [-Wunused-function]
 5820 | static u16 igb_select_queue(struct net_device *dev, struct sk_buff *skb,
      |            ^~~~~~~~~~~~~~~~
make[3]: *** [scripts/Makefile.build:279: /home/brandon/sourceforge/avb4linux/kernel-module/igb/igb_main.o] Error 1
make[2]: *** [Makefile:1597: _module_/home/brandon/sourceforge/avb4linux/kernel-module/igb] Error 2
make[2]: Leaving directory '/usr/lib/modules/5.2.11-arch1-1-ARCH/build'
make[1]: *** [Makefile:264: default] Error 2
make[1]: Leaving directory '/home/brandon/sourceforge/avb4linux/kernel-module/igb'
make: *** [Makefile:31: igb] Error 2

I am sorry if this is a silly thing that I just don't know what I am doing. What could this be? 

(Also, thanks so much for all of your help)

**Comment by Drumfix** [comment]
Replace: 

```
#ifdef HAVE_NDO_SELECT_QUEUE_ACCEL_FALLBACK
#if LINUX_VERSION_CODE >= KERNEL_VERSION(5,0,0)
static u16 igb_select_queue(struct net_device *dev, struct sk_buff *skb,
			    struct net_device *sb_dev, select_queue_fallback_t fallback);
#else
static u16 igb_select_queue(struct net_device *dev, struct sk_buff *skb,
			    void *accel_priv, select_queue_fallback_t fallback);
#endif
#else
static u16 igb_select_queue(struct net_device *dev, struct sk_buff *skb);
#endif

```
by:

```
static u16 igb_select_queue(struct net_device *dev, struct sk_buff *skb,
			    struct net_device *sb_dev);

```

and further down

```
#ifdef HAVE_NDO_SELECT_QUEUE_ACCEL_FALLBACK
#if LINUX_VERSION_CODE >= KERNEL_VERSION(5,0,0)
static u16 igb_select_queue(struct net_device *dev, struct sk_buff *skb,
			    struct net_device *sb_dev, select_queue_fallback_t fallback)
#else
static u16 igb_select_queue(struct net_device *dev, struct sk_buff *skb,
			    void *accel_priv, select_queue_fallback_t fallback)
#endif
#else
static u16 igb_select_queue(struct net_device *dev, struct sk_buff *skb)
#endif
{
	/* remap normal LAN to best effort queue[3] */
	return 3;
}

```
by

```
static u16 igb_select_queue(struct net_device *dev, struct sk_buff *skb,
			    struct net_device *sb_dev)
{
	/* remap normal LAN to best effort queue[3] */
	return 3;
}

```

**Comment by brandflake11** [comment]
Thanks so much for your help, this compiled and installed with your fixes! I'll let you know if anything else comes up!
